.class public final Lc5/o$a$i;
.super Lkotlin/jvm/internal/Lambda;
.source ""

# interfaces
.implements Lkotlin/jvm/functions/Function0;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lc5/o$a;-><init>(Lc5/o;)V
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lkotlin/jvm/internal/Lambda;",
        "Lkotlin/jvm/functions/Function0<",
        "Li5/e;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic a:Lc5/o;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lc5/o<",
            "TT;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lc5/o;)V
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lc5/o<",
            "TT;>;)V"
        }
    .end annotation

    iput-object p1, p0, Lc5/o$a$i;->a:Lc5/o;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lkotlin/jvm/internal/Lambda;-><init>(I)V

    return-void
.end method


# virtual methods
.method public invoke()Ljava/lang/Object;
    .registers 5

    iget-object v0, p0, Lc5/o$a$i;->a:Lc5/o;

    sget v1, Lc5/o;->e:I

    invoke-virtual {v0}, Lc5/o;->r()Lh6/b;

    move-result-object v0

    iget-object v1, p0, Lc5/o$a$i;->a:Lc5/o;

    iget-object v1, v1, Lc5/o;->d:Lc5/p0$b;

    invoke-virtual {v1}, Lc5/p0$b;->invoke()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lc5/o$a;

    iget-object v1, v1, Lc5/t$b;->a:Lc5/p0$a;

    sget-object v2, Lc5/t$b;->b:[Lz4/n;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    invoke-virtual {v1}, Lc5/p0$a;->invoke()Ljava/lang/Object;

    move-result-object v1

    const-string v2, "<get-moduleData>(...)"

    invoke-static {v1, v2}, Lkotlin/jvm/internal/Intrinsics;->checkNotNullExpressionValue(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, Ln5/i;

    iget-boolean v2, v0, Lh6/b;->c:Z

    if-eqz v2, :cond_2f

    iget-object v1, v1, Ln5/i;->a:Lu6/k;

    invoke-virtual {v1, v0}, Lu6/k;->b(Lh6/b;)Li5/e;

    move-result-object v0

    goto :goto_37

    :cond_2f
    iget-object v1, v1, Ln5/i;->a:Lu6/k;

    iget-object v1, v1, Lu6/k;->b:Li5/e0;

    invoke-static {v1, v0}, Li5/w;->a(Li5/e0;Lh6/b;)Li5/e;

    move-result-object v0

    :goto_37
    if-nez v0, :cond_c1

    iget-object p0, p0, Lc5/o$a$i;->a:Lc5/o;

    iget-object v0, p0, Lc5/o;->c:Ljava/lang/Class;

    invoke-static {v0}, Ln5/e;->a(Ljava/lang/Class;)Ln5/e;

    move-result-object v0

    if-eqz v0, :cond_4a

    iget-object v0, v0, Ln5/e;->b:Lb6/a;

    if-eqz v0, :cond_4a

    iget-object v0, v0, Lb6/a;->a:Lb6/a$a;

    goto :goto_4b

    :cond_4a
    const/4 v0, 0x0

    :goto_4b
    if-nez v0, :cond_4f

    const/4 v1, -0x1

    goto :goto_57

    :cond_4f
    sget-object v1, Lc5/o$b;->a:[I

    invoke-virtual {v0}, Ljava/lang/Enum;->ordinal()I

    move-result v2

    aget v1, v1, v2

    :goto_57
    packed-switch v1, :pswitch_data_c2

    :pswitch_5a  #0x0
    new-instance p0, Lh4/h;

    invoke-direct {p0}, Lh4/h;-><init>()V

    throw p0

    :pswitch_60  #0x5
    new-instance v1, Lc5/n0;

    const-string v2, "Unknown class: "

    invoke-static {v2}, Ld/c;->a(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    iget-object p0, p0, Lc5/o;->c:Ljava/lang/Class;

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string p0, " (kind = "

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 p0, 0x29

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v1, p0}, Lc5/n0;-><init>(Ljava/lang/String;)V

    throw v1

    :pswitch_82  #0x4
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "

    invoke-static {v1}, Ld/c;->a(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object p0, p0, Lc5/o;->c:Ljava/lang/Class;

    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_97  #0x1, 0x2, 0x3
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "

    invoke-static {v1}, Ld/c;->a(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object p0, p0, Lc5/o;->c:Ljava/lang/Class;

    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_ac  #0xffffffff, 0x6
    new-instance v0, Lc5/n0;

    const-string v1, "Unresolved class: "

    invoke-static {v1}, Ld/c;->a(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object p0, p0, Lc5/o;->c:Ljava/lang/Class;

    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Lc5/n0;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_c1
    return-object v0

    :pswitch_data_c2
    .packed-switch -0x1
        :pswitch_ac  #ffffffff
        :pswitch_5a  #00000000
        :pswitch_97  #00000001
        :pswitch_97  #00000002
        :pswitch_97  #00000003
        :pswitch_82  #00000004
        :pswitch_60  #00000005
        :pswitch_ac  #00000006
    .end packed-switch
.end method
